# Change these first
owner: grahamsh-llk # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: GrahamSH.com
    url: https://grahamsh.com
  - name: IsOffline
    url: https://isoffline.grahamsh.com/status/grahamsh
  - name: Ejenda
    url: https://ejenda.org
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.grahamsh.com
  logoUrl: https://avatars.githubusercontent.com/u/64214252
  name: GrahamSH Status
  introTitle: "**Status for GrahamSH Websites**"
  introMessage: Monitors important sites run by Graham
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
